### ISSUE TITLE
Error in Safe\preg_match()

### ISSUE THREAD

**Issue by temp** [thecodingmachine/safe#30] opened 2018-09-14 09:25 UTC
Transition from:
```
\preg_match('/foo/' 'foobar', $match);
var_dump($match);
```
To:
```
\Safe\preg_match('/foo/' 'foobar', $match);
var_dump($match);
```
Will differ, since there is a null-check for $match in the wrapper function, and match hasn't been initialized yet. 
People might stumble over that.

**Comment by moufmouf** [comment] 2018-09-14 11:48
Hey @temp .

This is a duplicate of #26 that was fixed a few hours ago.
Try to `composer update`, the issue should be fixed now.

**Closed by moufmouf** 2018-09-14 11:48 UTC
Labels: duplicate
