### ISSUE TITLE
 "php": "^7.2|^8.0"

### ISSUE THREAD

**Issue by umpirsky** [thecodingmachine/safe#331] opened 2022-02-28 11:32 UTC
Currently it's not possible to run this package with PHP 7.3 and 8.0 at the same time.

This is especially problematic in multi-server environment, where servers are upgraded one by one.

Can we have at least one version (`1.3.4`) that supports this please? I guess this one should have https://github.com/thecodingmachine/safe/pull/273 in it too.

I can help preparing the branch if there is interest. 

Thanks.

**Comment by dbrekelmans** [comment] 2022-03-10 09:40
Hi @umpirsky, unfortunately that's not possible at the moment because function signatures have changed between versions. We've created https://github.com/thecodingmachine/safe/issues/317 in order to make this possible.
Nobody is currently working on it, so if you're up for it, go ahead!

**Comment by dbrekelmans** [comment] 2022-08-04 14:15
Closing this, as duplicate of #317

**Closed by dbrekelmans** 2022-08-04 14:15 UTC
