### ISSUE TITLE
\array is not array

### ISSUE THREAD

**Issue by snapshotpl** [thecodingmachine/safe#343] opened 2022-04-19 08:52 UTC
#333 introduces change where return type with `array` is defined as:
```
@return \array Returns an array.
```
phpstan doesn't recognize now it as array, so it's break things

**Comment by Kharhamel** [comment] 2022-04-19 11:53
I switched the tag 2.2 to pre-release, hopefully that will give us some time. But i am not really sure how to fix this. @j3j5 do you have an idea?

**Comment by Kharhamel** [comment] 2022-04-19 12:05
I think I am going to revert the j3j5 array rename PR and then i will create a beta to try his other strategy.

**Comment by j3j5** [comment] 2022-04-19 16:51
Ok, I think it may be time to report this on the phpdocparser repo, let me put together an issue as soon as I have time.

For some reason I don't get any error when testing on the [testing repo ](https://github.com/nepda/phpstan-larastan-bug) that was around, but I see now that phpstan doesn't support this form of return type (I should have checked earlier). Sorry about that :(

**Comment by j3j5** [comment] 2022-04-19 22:23
I opened [the issue on phpdoc-parser](https://github.com/phpstan/phpdoc-parser/issues/117) and although it was the wrong place to open it, it got some interesting insights on the replies, it may be that the issue was on larastan after all :see_no_evil: Let's see what Ondrej thinks about the proposed solution, also, need to find the time to test bleeding edge with his version, it may be fixed there already (although from the comments, I think the issue is on larastan).

Anyway, I'd hold on on merging this until we get a bit further on the discussion.

**Comment by j3j5** [comment] 2022-04-20 12:59
The comment above was meant for #338, anyway, looking at the responses by Jan on the other issue and after doing some more reading, I think he's right and the directory structure is wrong, so I believe #338 isn't the right answer either.

**Comment by Kharhamel** [comment] 2022-05-02 14:22
I am closing this thread since the original issue was solved

**Closed by Kharhamel** 2022-05-02 14:22 UTC
